### ISSUE TITLE
Andresito edita las fotitos

### ISSUE THREAD

**Issue by guilletrejo** [nestormann/parapam#4]
![fondobeta](https://user-images.githubusercontent.com/26556864/27409390-a3fb04d8-56b7-11e7-99d1-349c528f4adc.png)

Obtener una imagen .png de la pelota sola sin fondo
Idem para el arquero parado en el medio
Idem para el arquero tirado a la derecha
Idem para el arquero tirado a la izquierda

**Comment by nestormann** [comment]
Hecho
